apiVersion: v1
kind: Service
metadata:
  name: confluent
  namespace: default
  labels:
    k8s-app: confluent
spec:
#  ExternalName: ""
  type: NodePort
  ports:
  - name: "kafka"
    nodePort: 31200
    port: 9200
  - name: "schema-registry"
    nodePort: 31300
    port: 8081
  selector:
    k8s-app: confluent
status:
  loadBalancer: {}
