---
version: '2'
services:
    schema-registry:
        image: jeqo/confluent-platform-schema-registry:3.0.0
        environment:
          ZOOKEEPER_HOST: zookeeper
          ZOOKEEPER_PORT: 2181
        ports:
          - "8081:8081"
        links:
          - zookeeper
    kafka:
        image: jeqo/confluent-platform-kafka:3.0.0
        environment:
          ZOOKEEPER_HOST: zookeeper
          ZOOKEEPER_PORT: 2181
        ports:
          - "9092:9092"
        links:
          - zookeeper
    zookeeper:
        image: jeqo/confluent-platform-zookeeper:3.0.0
        ports:
          - "2181:2181"
