---
version: '2'
services:
    schema-registry:
        image: jeqo/confluent-platform-schema-registry:3.0.0-jdk8
        ports:
          - "8081:8081"
        depends_on:
          - kafka
        links:
          - zookeeper:zookeeper
          - kafka:kafka
    kafka:
        image: jeqo/confluent-platform-kafka:3.0.0-jdk8
        ports:
          - "9092:9092"
        depends_on:
          - zookeeper
        links:
          - zookeeper:zookeeper
    zookeeper:
        image: jeqo/confluent-platform-zookeeper:3.0.0-jdk8
        ports:
          - "2181:2181"
