- hosts: localhost
  vars:
    confluent_version: 3.1
    confluent_release: 3.1.1
    confluent_scala_version: 2.11
  tasks:
    - set_fact:
        base_image: jeqo/confluent-platform-base
        kafka_image: jeqo/confluent-platform-kafka:{{ confluent_release }}-{{ confluent_scala_version }}
        zookeeper_image: jeqo/confluent-platform-zookeeper:{{ confluent_release }}-{{ confluent_scala_version }}
        registry_image: jeqo/confluent-platform-schema-registry:{{ confluent_release }}-{{ confluent_scala_version }}

    - name: building {{ base_image }}
      docker_image:
        name: "{{ base_image }}"
        path: .
        buildargs:
          confluent_version: "{{ confluent_version }}"
          confluent_release: "{{ confluent_release }}"
          confluent_scala_version: "{{ confluent_scala_version }}"
        force: yes
        nocache: yes
        push: no
      register: result

    - debug:
        var: result

    - name: building {{ kafka_image }}
      docker_image:
        name: "{{ kafka_image }}"
        path: kafka
        force: yes
        nocache: yes
        push: yes
        pull: no
      register: result

    - debug:
        var: result

    - name: building {{ zookeeper_image }}
      docker_image:
        name: "{{ zookeeper_image }}"
        path: zookeeper
        force: yes
        nocache: yes
        push: yes
        pull: no
      register: result

    - debug:
        var: result

    - name: building {{ registry_image }}
      docker_image:
        name: "{{ registry_image }}"
        path: schema-registry
        force: yes
        nocache: yes
        push: yes
        pull: no
      register: result

    - debug:
        var: result
